openapi: 3.0.0
info:
  title: Harvester Admin API
  version: v0.1
paths:
  /harvester-admin/harvestables:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    post:
      description: Create harvest job configuration
      operationId: postHarvestable
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/harvestable"
        required: true
      responses:
        "204":
          description: Harvest definition created
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    get:
      description: Get brief harvest job definitions
      operationId: getHarvestables
      parameters:
      - in: query
        name: query
        required: false
        description: CQL
        schema:
          type: string
      responses:
        "200":
          description: Harvest job definitions returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/harvestables"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/harvestables/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: Harvest configuration identifier
        schema:
          type: string
    get:
      operationId: getHarvestable
      description: Get harvest configuration
      responses:
        "200":
          description: Harvest configuration returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/harvestable"
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      operationId: deleteHarvestable
      description: Delete a harvest job configuration
      responses:
        "204":
          description: Harvest job configuration deleted
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/harvestables/{id}/log:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: Harvest configuration identifier
        schema:
          type: string
    get:
      operationId: getJobLog
      description: Get harvest configuration
      responses:
        "200":
          description: Harvest configuration returned
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/storages:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    post:
      description: Create storage configuration
      operationId: postStorage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/storage"
        required: true
      responses:
        "204":
          description: Storage definition created
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    get:
      description: Get brief storage definitions
      operationId: getStorages
      parameters:
        - in: query
          name: query
          required: false
          description: CQL
          schema:
            type: string
      responses:
        "200":
          description: Storage definitions returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/storages"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/storages/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: Storage definition identifier
        schema:
          type: string
    get:
      operationId: getStorage
      description: Get storage definition
      responses:
        "200":
          description: Storage definitions returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/storage"
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    put:
      operationId: putStorage
      description: Update storage definition
      responses:
        "204":
          description: No content
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      operationId: deleteStorage
      description: Delete a storage definition
      responses:
        "204":
          description: Storage definition deleted
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/transformations:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    post:
      description: Create transformation pipeline
      operationId: postTransformation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/transformation"
        required: true
      responses:
        "204":
          description: Storage definition created
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    get:
      description: Get brief transformation definitions
      operationId: getTransformations
      parameters:
        - in: query
          name: query
          required: false
          description: CQL
          schema:
            type: string
      responses:
        "200":
          description: Transformation pipelines returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transformations"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/transformations/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: Transformation pipeline identifier
        schema:
          type: string
    get:
      operationId: getTransformation
      description: Get transformation pipeline
      responses:
        "200":
          description: Transformation pipelines returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transformation"
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    put:
      operationId: putTransformation
      description: Update transformation pipeline
      responses:
        "204":
          description: No content
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      operationId: deleteTransformation
      description: Delete a transformation pipeline
      responses:
        "204":
          description: Transformation pipeline deleted
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/steps:
    get:
      operationId: getSteps
      description: Get brief transformation step definition records
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/steps"
        "500":
          $ref: "#/components/responses/trait_500"
    post:
      operationId: postStep
      description: Create new transformation step definition
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/step"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/step"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      operationId: deleteSteps
      description: Delete all transformation step definitions
      responses:
        "204":
          description: No content
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/steps/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: Step identifier
        schema:
          type: string
    get:
      operationId: getStep
      description: Get detailed transformation step definition record
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/step"
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    put:
      operationId: putStep
      description: Update a transformation step definition
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/step"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/step"
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      operationId: deleteStep
      description: Delete a transformation step definition
      responses:
        "204":
          description: No content
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/steps/{id}/script:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: Step identifier
        schema:
          type: string
    get:
      operationId: getScript
      description: Get transformation step script
      responses:
        "200":
          description: OK
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/script"
        "500":
          $ref: "#/components/responses/trait_500"
    put:
      operationId: putScript
      description: Update a transformation step script
      requestBody:
        content:
          application/xml:
            schema:
              $ref: "#/components/schemas/script"
      responses:
        "204":
          description: OK, no content
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/tsas:
    get:
      operationId: getTsas
      description: Get transformation step associations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transformationStepAssociations"
        "500":
          $ref: "#/components/responses/trait_500"
    post:
      operationId: postTsa
      description: Create new transformation step association
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/transformationStepAssociation"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transformationStepAssociation"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      operationId: deleteTsas
      description: Delete all transformation step associations
      responses:
        "204":
          description: No content
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

  /harvester-admin/tsas/{id}:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: path
        name: id
        required: true
        description: Association identifier
        schema:
          type: string
    get:
      operationId: getTsa
      description: Get a transformation step association
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transformationStepAssociation"
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    put:
      operationId: putTsa
      description: Update a transformation step association
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/transformationStepAssociation"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transformationStepAssociation"
        "400":
          $ref: "#/components/responses/trait_400"
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"
    delete:
      operationId: deleteTsa
      description: Delete a transformation step association
      responses:
        "204":
          description: No content
        "404":
          $ref: "#/components/responses/trait_404"
        "500":
          $ref: "#/components/responses/trait_500"

components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: {"error":"Invalid JSON in request"}
    trait_404:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Not found
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
  schemas:
    harvestables:
      $ref: schemas/harvestables.json
    harvestable:
      $ref: schemas/harvestable.json
    storages:
      $ref: schemas/storages.json
    storage:
      $ref: schemas/storage.json
    transformations:
      $ref: schemas/transformations.json
    transformation:
      $ref: schemas/transformation.json
    steps:
      $ref: schemas/steps.json
    step:
      $ref: schemas/step.json
    script:
      $ref: schemas/script.json
    transformationStepAssociation:
      $ref: schemas/transformationStepAssociation.json
    transformationStepAssociations:
      $ref: schemas/transformationStepAssociations.json
