name: api-schema-lint

# https://dev.folio.org/guides/describe-schema/

env:
  API_DIRECTORIES: 'src/main/resources/openapi'
  API_EXCLUDES: 'example'

on:
  push:
    paths:
      - 'src/main/resources/openapi/**'
  pull_request:
    paths:
      - 'src/main/resources/openapi/**'

jobs:
  api-schema-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Prepare folio-tools
        run: |
          git clone https://github.com/folio-org/folio-tools
          cd folio-tools/api-schema-lint \
            && yarn install \
            && pip3 install -r requirements.txt
      - name: Do api-schema-lint
        run: |
          python3 folio-tools/api-schema-lint/api_schema_lint.py \
            --loglevel info \
            --directories ${{ env.API_DIRECTORIES }} \
            --excludes ${{ env.API_EXCLUDES }}
