name: build-maven

on:
#  push:
#    paths-ignore:
#      - '**/*.[mM][dD]'
#      - '**/*.[tT][xX][tT]'
  workflow_dispatch:

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Gather some variables
        run: |
          echo "MODULE_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "MODULE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
      - name: Report dependencies that are snaphots
        run: mvn dependency:list | { grep -i snapshot || true; }
      - name: Do Maven build
        run: mvn clean install
      - name: Ensure built ModuleDescriptor
        run: |
          if test -f "$MOD_DESCRIPTOR"; then
            echo "Found $MOD_DESCRIPTOR"
            echo "MODULE_DESCRIPTOR=$MOD_DESCRIPTOR" >> $GITHUB_ENV
          else
            echo "Could not find $MOD_DESCRIPTOR"
            exit 1
          fi
        env:
          MOD_DESCRIPTOR: './target/ModuleDescriptor.json'
