name: test-login-registry-okclient

env:
  FOLIO_MD_REGISTRY: 'https://registry.folio-dev.indexdata.com'
  OK_SESSION: 'session1'

on:
  workflow_dispatch:
  push:
    branches: [ DEVOPS-3370-okclient-3 ]

jobs:
  test-login-registry-okclient:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare okclient
        run: git clone https://github.com/indexdata/okclient
      - name: Ensure login ModuleDescriptor registry
        # So do not proceed with other workflow steps if not available.
        run: |
          cd okclient && source ./ok.sh
          OK -S ${{ env.OK_SESSION }} \
            -h ${{ env.FOLIO_MD_REGISTRY }} \
            -t ${{ secrets.FOLIO_REGISTRY_TENANT }} \
            -u ${{ secrets.FOLIO_REGISTRY_USERNAME }} \
            -p ${{ secrets.FOLIO_REGISTRY_PASSWORD }}
          echo "F_HOST_VAR=${{ env.OK_SESSION }}_FOLIOHOST" >> $GITHUB_ENV
          # echo "F_HOST=${{ !env.F_HOST_VAR }" >> $GITHUB_ENV
          declare -n F_HOST_NAMEREF=${{ env.OK_SESSION }}_FOLIOHOST
          echo "F_HOST=$F_HOST_NAMEREF" >> $GITHUB_ENV
          # OK -S ${{ env.OK_SESSION }} -x
      - name: Set some variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      - name: Report some variables
        run: |
          echo "REPO_NAME=${{ env.REPO_NAME }}"
          echo "F_HOST_VAR=${{ env.F_HOST_VAR }}"
          echo "F_HOST=${{ env.F_HOST }}"
      - name: Do OK login and operations
        run: |
          cd okclient && source ./ok.sh
          OK -S ${{ env.OK_SESSION }} \
            -h ${{ env.FOLIO_MD_REGISTRY }} \
            -t ${{ secrets.FOLIO_REGISTRY_TENANT }} \
            -u ${{ secrets.FOLIO_REGISTRY_USERNAME }} \
            -p ${{ secrets.FOLIO_REGISTRY_PASSWORD }}
          for id in $(OK -S ${{ env.OK_SESSION }} _/proxy/modules?latest=1 -j '.[].id'); do
            printf "%s\n" "$id"
          done
          OK -S ${{ env.OK_SESSION }} -x
